%%% @author Jordi Chacon <jordi.chacon@gmail.com>
%%% @copyright (C) 2010, Jordi Chacon

-module(pongerl_client_utils).

-export([draw_number/4]).

-include_lib("../include/pongerl.hrl").
-include_lib("../dep/cecho/include/cecho.hrl").

draw_number(0, X, Y, _) ->
    cecho:attron(?ceCOLOR_PAIR(?RESULT_PAIR)),
    cecho:move(Y, X),
    cecho:addstr("      "),
    cecho:move(Y + 1, X),
    cecho:addstr("  "),
    cecho:move(Y + 1, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 2, X),
    cecho:addstr("  "),
    cecho:move(Y + 2, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 3, X),
    cecho:addstr("  "),
    cecho:move(Y +3 , X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 4, X),
    cecho:addstr("      "),
    cecho:refresh(),
    cecho:attroff(?ceCOLOR_PAIR(?RESULT_PAIR));
draw_number(1, X, Y, _) ->
    cecho:attron(?ceCOLOR_PAIR(?RESULT_PAIR)),
    cecho:move(Y, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 1, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 1, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 2, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 2, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 3, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 3, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 4, X + 4),
    cecho:addstr("  "),
    cecho:refresh(),
    cecho:attroff(?ceCOLOR_PAIR(?RESULT_PAIR));
draw_number(2, X, Y, _) ->
    cecho:attron(?ceCOLOR_PAIR(?RESULT_PAIR)),
    cecho:move(Y, X),
    cecho:addstr("      "),
    cecho:move(Y + 1, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 2, X),
    cecho:addstr("      "),
    cecho:move(Y + 3, X),
    cecho:addstr("  "),
    cecho:move(Y + 4, X),
    cecho:addstr("      "),
    cecho:refresh(),
    cecho:attroff(?ceCOLOR_PAIR(?RESULT_PAIR));
draw_number(3, X, Y, _) ->
    cecho:attron(?ceCOLOR_PAIR(?RESULT_PAIR)),
    cecho:move(Y, X),
    cecho:addstr("      "),
    cecho:move(Y + 1, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 2, X + 2),
    cecho:addstr("    "),
    cecho:move(Y + 3, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 4, X),
    cecho:addstr("      "),
    cecho:refresh(),
    cecho:attroff(?ceCOLOR_PAIR(?RESULT_PAIR));
draw_number(4, X, Y, _) ->
    cecho:attron(?ceCOLOR_PAIR(?RESULT_PAIR)),
    cecho:move(Y, X),
    cecho:addstr("  "),
    cecho:move(Y, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 1, X),
    cecho:addstr("  "),
    cecho:move(Y + 1, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 2, X),
    cecho:addstr("      "),
    cecho:move(Y + 3, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 3, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 4, X + 4),
    cecho:addstr("  "),
    cecho:refresh(),
    cecho:attroff(?ceCOLOR_PAIR(?RESULT_PAIR));
draw_number(5, X, Y, _) ->
    cecho:attron(?ceCOLOR_PAIR(?RESULT_PAIR)),
    cecho:move(Y, X),
    cecho:addstr("      "),
    cecho:move(Y + 1, X),
    cecho:addstr("  "),
    cecho:move(Y + 2, X),
    cecho:addstr("      "),
    cecho:move(Y + 3, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 4, X),
    cecho:addstr("      "),
    cecho:refresh(),
    cecho:attroff(?ceCOLOR_PAIR(?RESULT_PAIR));
draw_number(6, X, Y, _) ->
    cecho:attron(?ceCOLOR_PAIR(?RESULT_PAIR)),
    cecho:move(Y, X),
    cecho:addstr("      "),
    cecho:move(Y + 1, X),
    cecho:addstr("  "),
    cecho:move(Y + 2, X),
    cecho:addstr("      "),
    cecho:move(Y + 3, X),
    cecho:addstr("  "),
    cecho:move(Y + 3, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 4, X),
    cecho:addstr("      "),
    cecho:refresh(),
    cecho:attroff(?ceCOLOR_PAIR(?RESULT_PAIR));
draw_number(7, X, Y, _) ->
    cecho:attron(?ceCOLOR_PAIR(?RESULT_PAIR)),
    cecho:move(Y, X),
    cecho:addstr("      "),
    cecho:move(Y + 1, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 1, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 2, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 2, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 3, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 3, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 4, X + 4),
    cecho:addstr("  "),
    cecho:refresh(),
    cecho:attroff(?ceCOLOR_PAIR(?RESULT_PAIR));
draw_number(8, X, Y, _) ->
    cecho:attron(?ceCOLOR_PAIR(?RESULT_PAIR)),
    cecho:move(Y, X),
    cecho:addstr("      "),
    cecho:move(Y + 1, X),
    cecho:addstr("  "),
    cecho:move(Y + 1, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 2, X),
    cecho:addstr("      "),
    cecho:move(Y + 3, X),
    cecho:addstr("  "),
    cecho:move(Y + 3, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 4, X),
    cecho:addstr("      "),
    cecho:refresh(),
    cecho:attroff(?ceCOLOR_PAIR(?RESULT_PAIR));
draw_number(9, X, Y, _) ->
    cecho:attron(?ceCOLOR_PAIR(?RESULT_PAIR)),
    cecho:move(Y, X),
    cecho:addstr("      "),
    cecho:move(Y + 1, X),
    cecho:addstr("  "),
    cecho:move(Y + 1, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 2, X),
    cecho:addstr("      "),
    cecho:move(Y + 3, X + 4),
    cecho:addstr("  "),
    cecho:move(Y + 4, X),
    cecho:addstr("      "),
    cecho:refresh(),
    cecho:attroff(?ceCOLOR_PAIR(?RESULT_PAIR));
draw_number(N, X, Y, 1) ->
    FirstDigit = N div 10,
    SecondDigit = N rem 10,
    draw_number(FirstDigit, X - ?NX - 1, Y, 1),
    draw_number(SecondDigit, X, Y, 1);
draw_number(N, X, Y, 2) ->
    FirstDigit = N div 10,
    SecondDigit = N rem 10,
    draw_number(FirstDigit, X, Y, 1),
    draw_number(SecondDigit, X + ?NX + 1, Y, 1).
    
